#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# running phpstan
echo "Running phpstan"
./vendor/bin/phpstan analyse
if [ $? -ne 0 ]; then
    echo "Deu erro no phpstan"
    exit 1;
fi


# fomart each file changed with laravel pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

echo "Running Laravel Pint"
for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}";
    git add "${FILE}";
done;

exit 0;
